CREATE TABLE IF NOT EXISTS `tbl_usershops` (
`ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
`isActive` BOOLEAN NOT NULL ,
`shopFinished` BOOLEAN NOT NULL ,
`creationTime` INTEGER NOT NULL ,
`lastUsedTime` INTEGER NOT NULL ,
`xPos` INTEGER NOT NULL ,
`yPos` INTEGER NOT NULL ,
`zPos` INTEGER NOT NULL ,
`worldName` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `tbl_usershops_inventories` (
`ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
`ShopID` INTEGER NOT NULL ,
`TypeID` INTEGER NOT NULL ,
`SubID` INTEGER NOT NULL ,
`Amount` INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS `tbl_aliases` (
`ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
`playerName` TEXT NOT NULL ,
`aliasName` TEXT NOT NULL
);