name: BuyCraft
main: de.minestar.buycraft.core.Core
version: 1.4.6_1-SNAPSHOT
depend: [MineStarLibrary, FalseBookCore, MinestarCore]
commands:
  buycraft:
    description: BuyCraft-related commands
    usage: /<command>